name: Example using action to sign firmware for rp2350
on: [push]
jobs:
  sign-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Signing Action
        uses: immutaverse/rp2350-mkt-signer@main              
        with:
          # Path to the previously generated UF2 firmware file
          FIRMWARE: 'unsigned/blink_fast.uf2'

          # 'sign' to sign an existing firmware file.
          # 'build' to build the firmware from source and sign it.
          BUILD_ACTION: 'sign'
          
          # Path to the OTP firmware options file that will be
          # updated with the public key for signing.
          OTP_FILE: 'signed/blink_fast.otp.json'

          # The board name passed into the build scripts.
          # Normally only used when BUILD_ACTION = build.
          BOARD_NAME: 'pico2'

          # Source directory containing source code to build
          # with the SDK file. Mandatory when BUILD_ACTION = build.
          # Ignored when BUILD_ACTION = sign.
          SOURCE_DIR: 'NOT SET'

          # Metadata file that contains firmware signing metadata.
          # Not all chips use this; the RP2350 does not.
          SIGN_METADATA: 'NOT SET'
          
          # Base64 encoded private key, normally loaded from                 
          # GitHub secrets but can be provided from any source.
          PRIVATE_KEY: ${{ secrets.RP2350_SAMPLE_PRIVATE_KEY }}

          DOCKER_ACCESS_TOKEN: ${{ secrets.RP2350_DOCKER_ACCESS_KEY }}
        


      - name: Rename and Timestamp Signed Artifact
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          mkdir -p signed_artifacts
          mv docker_workspace/firmware.signed signed_artifacts/${TIMESTAMP}_firmware.signed

      - name: Commit and Push Signed Firmware
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add signed_artifacts/
          git commit -m "Add signed firmware $TIMESTAMP"
          git push origin main
          # joe234567891011136

          #demo-signing-token